WIDTH = 1024
HEIGHT = 728
GAME_WIDTH = 30
GAME_HEIGHT = 20
OBJECT_WIDTH = int(WIDTH / GAME_WIDTH)
OBJECT_HEIGHT = int(HEIGHT / GAME_HEIGHT)
ZOOM = 40 # en %
WIN = None

def calcX(x):
    return OBJECT_WIDTH * x

def calcY(y):
    return OBJECT_HEIGHT * y